# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build  corne nice_nano_v2 nice_view based on eyeslash'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_left", "eyelash_corne_right"]'
      alpha: '["qwerty"]'
      shield: '["nice_view"]'
      modules: '["a741725193/zmk-new_corne/main"]'
